// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBZTyVYtL4qg2-h_4ya9XeW09EFK5tKXg',
    appId: '1:912448881273:web:fec28c0ba4bb695de78aa8',
    messagingSenderId: '912448881273',
    projectId: 'pengajuan-judul-classification',
    authDomain: 'pengajuan-judul-classification.firebaseapp.com',
    storageBucket: 'pengajuan-judul-classification.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKmhKKoFl9tbMz8tlg3WnxrmpieqKVSvU',
    appId: '1:912448881273:ios:86b391111b8cd334e78aa8',
    messagingSenderId: '912448881273',
    projectId: 'pengajuan-judul-classification',
    storageBucket: 'pengajuan-judul-classification.appspot.com',
    iosClientId:
        '912448881273-ctfch4o9e4dml222u0cmv56ddh7g6lm3.apps.googleusercontent.com',
    iosBundleId: 'com.example.pengajuanJudulDashboard',
  );
}
